project_id = "rgfmvklcjnljsfsxztyi"

[functions.verify-worldid]
verify_jwt = false

[functions.helius-webhook]
verify_jwt = false

[functions.helius-setup]
verify_jwt = false

[functions.nft-metadata]
verify_jwt = false

[functions.clawkey-register]
verify_jwt = false

[functions.clawkey-status]
verify_jwt = false
